### PR TITLE
Concatenate instead of adding in U-Net layers

### PR DESCRIPTION
**Pull request by rsamf**
See https://github.com/kailashahirwar/tryondiffusion/issues/24

@tanayag 

Not sure if the order of channels matter

### CODE REVIEW

**Comment by tanayag** [comment]
The order of channels is not the problem, but network won't work, did you try to test it. You need to change the number of convolution channels while defining the conv layers. twice the number of channels will now convolute to same number of channels as before. Eg. 

self.block5_person will get 2048 channels instead of 1024, same for all the decoder layers in both UNets.

**Comment by tanayag** [comment]
@rsamf I added noise level later and tested it locally, but will add that too to the code. I pass random tensors as you can see after `if __name__ == "__main__"` line. For `noise_level` just pass `0.3`. For tensor device mismatch I'll quickly debug code and fix it, but the last time I checked everything was working fine.

**Comment by rsamf** [comment]
I figured out the mismatch device problem. This happens to me because the GaussianSmoothing object that becomes instantiated in the forward call of the network goes into the cpu by default.:
https://github.com/kailashahirwar/tryondiffusion/blob/51ff67ef8d537ef59f0e61d9d06150247feeeb56/network.py#L123
Can I suggest we move the smoothing object into the constructor of the UNet? This is so that the network module becomes defined with the model, and then when we move the model to the specified device like so:
https://github.com/kailashahirwar/tryondiffusion/blob/51ff67ef8d537ef59f0e61d9d06150247feeeb56/network.py#L856
all underlying network components go into the specified `device` .This just means that the `noise_level` will have to be passed on init of the UNet or underlying AttentionPool1d object if that's okay. If so, I can create the issue for it.

**Comment by tanayag** [comment]
Got it, I added Gaussian Smoothening later so I forgot to transfer the model to the device.

I didn't want to add it to the main constructor because we'll pass one of the parameters `sigma` and its value will keep changing during the training period. 

And you have to initialize model in the constructor, only if you have any learnable weights. In this case, consider it just as a function instead of a model, so we can put it in forward, no problem. 

If you want to work on this, you can raise a PR, I have created issue #32

**Comment by tanayag** [comment]
Seems good. Will merge it then.

**Review by kailashahirwar — APPROVED** [review]

**Pull request merged**
